[[constraint]]
  name = "github.com/OneOfOne/xxhash"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"
